let bancos = [
    '001 – Banco do Brasil S.A.',
    '341 – Banco Itaú S.A.',
    '033 – Banco Santander (Brasil) S.A.',
    '356 – Banco Real S.A. (antigo)',
    '652 – Itaú Unibanco Holding S.A.',
    '237 – Banco Bradesco S.A.',
    '745 – Banco Citibank S.A.',
    '399 – HSBC Bank Brasil S.A.',
    '104 – Caixa Econômica Federal',
    '389 – Banco Mercantil do Brasil S.A.',
    '453 – Banco Rural S.A.',
    '422 – Banco Safra S.A.',
    '633 – Banco Rendimento S.A.'];
let bancos2 = [
        '654 - BANCO A.J. RENNER S.A.',
        '246 - BANCO ABC BRASIL S.A.',
        '075 - BANCO ABN AMRO S.A.',
        '025 - BANCO ALFA S.A.',
        '641 - BANCO ALVORADA S.A.',
        '213 - BANCO ARBI S.A.',
        '024 - BANCO BANDEPE S.A.',
        '740 - BANCO BARCLAYS S.A.',
        '107 - BANCO BBM S/A',
        '096 - BANCO BM&FBOVESPA S.A.',
        '318 - BANCO BMG S.A.',
        '752 - BANCO BNP PARIBAS BRASIL S.A.',
        '248 - BANCO BOAVISTA INTERATLANTICO',
        '218 - BANCO BONSUCESSO S.A.',
        '063 - BANCO BRADESCARD S.A.',
        '036 - BANCO BRADESCO BBI S.A.',
        '122 - BANCO BRADESCO BERJ S.A.',
        '394 - BANCO BRADESCO FINANCIAMENTOS',
        '237 - BANCO BRADESCO S.A.',
        '208 - BANCO BTG PACTUAL S.A.',
        '473 - BANCO CAIXA GERAL - BRASIL',
        '412 - BANCO CAPITAL S.A.',
        '040 - BANCO CARGILL S.A.',
        '266 - BANCO CEDULA S.A.',
        '739 - BANCO CETELEM S.A.',
        '233 - BANCO CIFRA S.A.',
        '745 - BANCO CITIBANK S.A.',
        '241 - BANCO CLASSICO S.A.',
        '003 - BANCO DA AMAZONIA S.A.',
        '083 - BANCO DA CHINA BRASIL S.A.',
        '707 - BANCO DAYCOVAL S.A.',
        'M06 - BANCO DE LAGE LANDEN BRASIL',
        '456 - BANCO DE TOKYO-MITSUBISHI',
        '001 - BANCO DO BRASIL S.A.',
        '265 - BANCO FATOR S.A.',
        '224 - BANCO FIBRA S.A.',
        '626 - BANCO FICSA S.A.',
        'M18 - BANCO FORD S.A.',
        '121 - BANCO GERADOR S.A.',
        'M07 - BANCO GMAC S.A.',
        'M22 - BANCO HONDA S.A.',
        'M11 - BANCO IBM S.A.',
        '630 - BANCO INTERCAP S.A.',
        '077 - BANCO INTERMEDIUM S.A.',
        '249 - BANCO INVESTCRED UNIBANCO',
        '184 - BANCO ITAÚ BBA S.A.',
        '029 - BANCO ITAÚ BMG CONSIGNADO',
        '479 - BANCO ITAUBANK S.A.',
        '074 - BANCO J. SAFRA S.A.',
        '376 - BANCO J.P. MORGAN S.A.',
        '217 - BANCO JOHN DEERE S.A.',
        '076 - BANCO KDB DO BRASIL S.A.',
        '243 - BANCO MÁXIMA S.A.',
        'M12 - BANCO MAXINVEST S.A.',
        '389 - BANCO MERCANTIL DO BRASIL S.A.',
        '370 - BANCO MIZUHO DO BRASIL S.A.',
        '746 - BANCO MODAL S.A.',
        'M10 - BANCO MONEO S.A.',
        '066 - BANCO MORGAN STANLEY S.A.',
        '212 - BANCO ORIGINAL S.A.',
        'M17 - BANCO OURINVEST S.A.',
        '623 - BANCO PAN S.A.',
        '611 - BANCO PAULISTA S.A.',
        '613 - BANCO PECUNIA S.A.',
        '094 - BANCO PETRA S.A.',
        '643 - BANCO PINE S.A.',
        '735 - BANCO POTTENCIAL S.A.',
        'M24 - BANCO PSA FINANCE BRASIL S.A.',
        '088 - BANCO RANDON S.A.',
        '633 - BANCO RENDIMENTO S.A.',
        '741 - BANCO RIBEIRAO PRETO S.A.',
        '120 - BANCO RODOBENS S.A.',
        '422 - BANCO SAFRA S.A.',
        '033 - BANCO SANTANDER (BRASIL) S.A.',
        '743 - BANCO SEMEAR S.A.',
        '754 - BANCO SISTEMA S.A.',
        '366 - BANCO SOCIETE GENERALE BRASIL',
        '637 - BANCO SOFISA S.A.',
        '464 - BANCO SUMITOMO MITSUI BRASILEIRO',
        '082 - BANCO TOPÁZIO S.A.',
        'M20 - BANCO TOYOTA DO BRASIL S.A.',
        '634 - BANCO TRIANGULO S.A.',
        '018 - BANCO TRICURY S.A.',
        'M14 - BANCO VOLKSWAGEN S.A.',
        'M23 - BANCO VOLVO BRASIL S.A.',
        '655 - BANCO VOTORANTIM S.A.',
        '610 - BANCO VR S.A.',
        '119 - BANCO WESTERN UNION DO BRASIL S.A.',
        '124 - BANCO WOORI BANK DO BRASIL S.A.',
        '081 - BBN BANCO BRASILEIRO DE NEGÓCIOS',
        '250 - BCV - BANCO DE CRÉDITO E VAREJO S/A',
        '017 - BNY MELLON BANCO S.A.',
        '069 - BPN BRASIL BANCO MÚLTIPLO S.A.',
        '125 - BRASIL PLURAL S.A. ',
        '070 - BRB - BANCO DE BRASILIA S.A.',
        '104 - CAIXA ECONOMICA FEDERAL',
        '477 - CITIBANK N.A.',
        '487 - DEUTSCHE BANK S.A.',
        '062 - HIPERCARD BANCO MÚLTIPLO ',
        '399 - HSBC BANK BRASIL S.A.',
        '132 - ICBC DO BRASIL ',
        '492 - ING BANK N.V.',
        '652 - ITAÚ UNIBANCO HOLDING S.A.',
        '341 - ITAÚ UNIBANCO S.A.',
        '014 - NATIXIS BRASIL S.A. ',
        '753 - NOVO BANCO CONTINENTAL S.A.',
        '254 - PARANÁ BANCO S.A.',
        '751 - SCOTIABANK BRASIL S.A. '];